FROM python:3.7
 
WORKDIR /api
ADD /api/requirements.txt /api/requirements.txt 
RUN pip install -r requirements.txt --no-cache-dir

COPY data/model.ftz data/model.ftz

COPY /api /api
 
EXPOSE 5000

ENTRYPOINT ["python"]
CMD ["main.py"]