ENHET_NACE_CSV_FILE_NAME = "nacekoder.tab"
ENHET_FORMAAL_CSV_FILE_NAME = "formaal.tab"
NACE_EXCEL_FILE_NAME = "nace.xlsx"
ASSEMBLED_DATA_FILE_NAME = "assembled_data.csv"
PREPROCESSED_DATA_FILE_NAME = "preprocessed_data.csv"
PROCESSED_DATA_FILE_NAME = "processed_data.csv"
TRAINING_SET_FILE_NAME = "training_set.csv"
VALIDATION_SET_FILE_NAME = "validation_set.csv"
TESTING_SET_FILE_NAME = "testing_set.csv"
TEST_RESULTS_FILE_NAME = "test_results.csv"
APPLY_TO_INPUT_FILE_NAME = "applied.csv"
MODEL_FILE_NAME = "model.ftz"

ORGNR_FIELD_NAME = "orgnr"
NACE1_FIELD_NAME = "nace1"
NACE2_FIELD_NAME = "nace2"
NACE3_FIELD_NAME = "nace3"
AKTIVITET_FIELD_NAME = "aktivitet"
